# Generated by Django 4.1 on 2022-08-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_project2_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=25)),
                ('data', models.JSONField()),
            ],
        ),
    ]
