# Generated by Django 4.1 on 2022-08-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project2',
        ),
    ]
