# Generated by Django 4.1 on 2022-08-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_delete_project2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='data',
        ),
    ]
