# Generated by Django 4.1 on 2022-08-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_project_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.JSONField(default={'div': 'div'}),
        ),
    ]
