# Generated by Django 4.1 on 2022-08-20 12:49

from django.db import migrations
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_project_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=web.models.CustomJsonField(default={'div': 'div'}),
        ),
    ]
