# Generated by Django 4.1 on 2022-08-20 14:55

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_project_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('single', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WidgetProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parrentId', models.BigIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('measure', models.CharField(max_length=10)),
                ('defaultValue', models.CharField(max_length=25)),
                ('values', web.models.CustomJsonField(default=['none', ''])),
                ('additionalData', web.models.CustomJsonField(default=['#ffffff', '#000000', 'rgb(255, 120, 0)'])),
            ],
        ),
    ]
