# Generated by Django 4.1 on 2022-08-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_widget_widgetproperty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widgetproperty',
            old_name='parrentId',
            new_name='parentId',
        ),
    ]
